# Generated by Django 5.2.17 on 2026-08-18 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.PositiveIntegerField(default=5)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalog.categoria')),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalog.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_RIR', 'Entrada (RIR Aprovado)'), ('SAIDA_VENDA', 'Saída (Venda)'), ('TRANSFERENCIA', 'Transferência entre Polos'), ('AJUSTE', 'Ajuste Manual (Perda/Quebra)'), ('DEVOLUCAO', 'Devolução ao Fornecedor')], max_length=20)),
                ('quantidade', models.IntegerField(help_text='Valores positivos para entrada, negativos para saída.')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.polo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='accounts.polo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_polo', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'Estoque do Polo',
                'verbose_name_plural': 'Estoques dos Polos',
                'unique_together': {('polo', 'produto')},
            },
        ),
    ]
